---
- name: Install cpupower on Debian
  package:
    name: linux-cpupower
    state: present
  when: ansible_distribution == "Debian"

- name: Install cpupower on Ubuntu (tools package)
  package:
    name:
      - linux-tools-common
      - linux-tools-generic
      - "linux-tools-{{ ansible_kernel }}"
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Get current GRUB command line safely
  shell: |
    if [ -f /etc/default/grub ] && grep -q '^GRUB_CMDLINE_LINUX=' /etc/default/grub; then
      grep '^GRUB_CMDLINE_LINUX=' /etc/default/grub | cut -d= -f2- | tr -d '"'
    else
      echo ""
    fi
  register: current_grub_cmdline  
  changed_when: false

- name: Check if processor.max_cstate is already set correctly
  set_fact:
    cstates_already_disabled: "{{ current_grub_cmdline.stdout is regex('(^| )processor\\.max_cstate=' ~ target_cstate ~ '($| )') }}"

- name: Remove any existing processor.max_cstate
  replace:
    path: /etc/default/grub
    regexp: '(GRUB_CMDLINE_LINUX=".*?)( processor\.max_cstate=\d+)(.*")'
    replace: '\1\3'
  when: not cstates_already_disabled  

- name: Add processor.max_cstate={{ target_cstate }}
  replace:
    path: /etc/default/grub
    regexp: '(GRUB_CMDLINE_LINUX=")(.*)(")'
    replace: '\1\2 processor.max_cstate={{ target_cstate }}\3'
  when: not cstates_already_disabled
  notify: update grub

- name: Check CPU frequency scaling availability
  stat:
    path: /sys/devices/system/cpu/cpu0/cpufreq
  register: cpufreq_dir
  changed_when: false

- name: Set CPU governor to performance if available
  block:
    - name: Check available governors
      shell: cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors 2>/dev/null || echo ""
      register: available_governors
      changed_when: false
      when: cpufreq_dir.stat.exists

    - name: Set performance governor via sysfs
      shell: |
        for cpu in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do
          echo "performance" > "$cpu" 2>/dev/null || true
        done
      when:
        - cpufreq_dir.stat.exists
        - "'performance' in available_governors.stdout"

    - name: Set governor via cpupower if available
      command: cpupower frequency-set -g performance
      when: install_cpupower is success and not cpufreq_dir.stat.exists
      ignore_errors: true

  rescue:
    - name: Warn about governor management
      debug:
        msg: "CPU governor management not available or failed"
      changed_when: false
