---
- name: update grub
  command: update-grub
  listen: "update grub"

- name: apply netplan
  command: netplan apply

- name: reboot for system changes
  reboot:
    msg: "Rebooting to apply interface renaming and other system changes"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
